name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: maissacrement
        password: ${{ secrets.GITLAB_PASS }}
    - name: Build Tag Update
      run: make build tag
    - name: Push
      run: |
        docker push maissacrement/docker/radio:latest