name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: docker login registry.gitlab.com -u ${GITLAB_USER} -p ${GITLAB_PASS}
    - name: Build Tag Update
      run: make push USER=${GITLAB_USER} PASS=${GITLAB_PASS}
